name: Create Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Get tag name
          TAG_NAME=${GITHUB_REF#refs/tags/}
          
          # Create release
          gh release create "$TAG_NAME" \
            --title "Release $TAG_NAME" \
            --draft=false \
            --prerelease=false \
            main.js manifest.json styles.css \
            --generate-notes
